### ISSUE TITLE
Multiple Redelgation

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#101]
Redelegate from and to several validators at once.

**Comment by kwunyeung** [comment]
node01 is also building similar thing. We can take it as a reference.

https://twitter.com/01node/status/1135900087039774720

**Comment by clawmvp** [comment]
https://irisnet-delegator-test.web.app/ give it a spin :)

**Comment by kwunyeung** [comment]
> https://irisnet-delegator-test.web.app/ give it a spin :)

You rock!

**Comment by ztsai** [comment]
#97

**Comment by kwunyeung** [comment]
This will be done in BD Wallet.
