### ISSUE TITLE
The info changed for the validator was not reflected correctly

### ISSUE THREAD

**Issue by calvinzhou-rockx** [forbole/big-dipper#191]
**Describe the bug**
I have a validator setup wrongly and updated all the info, but it still shows the outdated messages in : https://cosmos.bigdipper.live/validator/240DE97689433F94FA8A9961E2A0405A0B6080C3

The name of the validator was updated to "Deparecated" and the logo was removed, detailed message also changed. 

Please help to check why it still caches the outdated message

Thanks

**To Reproduce**
Just click : https://cosmos.bigdipper.live/validator/240DE97689433F94FA8A9961E2A0405A0B6080C3
The info is different from the blockchain 

**Expected behavior**
Should show no logo and the validator name to "Deparecated" 

It happened in any browser

**Comment by kwunyeung** [comment]
This should be an issue related to the backend not indexing inactive validators correctly. From 

https://github.com/forbole/big_dipper/blob/master/imports/api/blocks/server/methods.js#L161

it tries to read all validators from bonding/unbonding/unbonded status into a list and update the data. I believe at some point it doesn't update the data of the unbonding and unbonded validators and it makes the validators not being displayed correct when they have been unbonded.
