### ISSUE TITLE
Ledger support in Win10 is broken

### ISSUE THREAD

**Issue by williamchong** [forbole/big-dipper#213]
**Describe the bug**
On windows 10, I cannot login via ledger cosmos app. The USB popups flashes for a few times then the ledger is stuck in `Returning Address` and the website shows an error message.

**To Reproduce**
1. Go to bigdipper
2. Click on the top right key icon to login
3. Wait for sign in with ledger dialog to load and connects to ledger
4. See the windows USB dialog popup and disappears for a few times
5. Press confirm on Ledger, Ledger is stuck in `Returning Address` , web dialog returns error

**Expected behavior**
Bigdipper should receive my cosmos address and sign me in after I press confirm

**Screenshots**
![image](https://user-images.githubusercontent.com/6198816/69114805-648ab800-0ac1-11ea-92ce-83dd178d43fe.png)
![image](https://user-images.githubusercontent.com/6198816/69114818-69e80280-0ac1-11ea-9ffb-4fbf1a453b9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser: Chrome
 - Version 78.0.3

**Additional context**
Probably similar to https://github.com/luniehq/lunie/issues/2754

**Comment by kwunyeung** [comment]
Thank you for the report. This is a known issue. We are planning to integrate with the latest `cosmos-ledger-js` which should fix this and working with the upcoming `Cosmos App v2.0`. #183

**Comment by kwunyeung** [comment]
https://github.com/luniehq/lunie/pull/3248

**Comment by kwunyeung** [comment]
https://github.com/cosmos/ledger-cosmos/issues/157#issuecomment-561375368
