### ISSUE TITLE
The estimated value became NaN

### ISSUE THREAD

**Issue by yookoala** [forbole/big-dipper#225]
**Describe the bug**
The estimated value of validator's balance became `NaN` for some reason:

**To Reproduce**
1. Go to https://likecoin.bigdipper.live/account/cosmos1nuvjepa3hc6av4awukvynwdrn0kjmqdf4ears0

**Expected behavior**
Expected to see an actual number.

**Screenshots**
![2019-12-09 10-20-06 的螢幕擷圖](https://user-images.githubusercontent.com/91274/70402214-9c0bd500-1a6d-11ea-86d5-e7cc5d526962.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox (70.0.1) and Chrome (78.0.3904.108)

**Additional context**
The current value of each coin (LIKECOIN) is $0.00000263, as displayed by Big Dipper:
![2019-12-09 10-48-51 的螢幕擷圖](https://user-images.githubusercontent.com/91274/70403385-a4fea580-1a71-11ea-8a23-1ea22132bebd.png)

**Comment by nnkken** [comment]
Seems related to the crawling of price info.
Previously, the crawling was disabled, so the price displayed was old and it shows NaN in estimated value.
Now the crawling is re-enabled (thanks @kwunyeung ), the NaN problem disappeared.

I may write a PR for properly disabling price crawling and display later.

**Comment by kwunyeung** [comment]
Yes, when there is no price feed, the calculation can't get a value.

**Comment by kwunyeung** [comment]
Should have fixed.
