### ISSUE TITLE
Which fields are needed in the settings file? Possible working example of one?

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#270]
Hi. 

I am delighted to see that Big Dipper is open source and available to be used on custom Cosmos chains.

I am having trouble getting it to work properly and would like to ask for help.

For starters, which fields are needed in the settings file? There are many and I don't even understand some of them. 

Is there some documentation that can explain what they mean? Many are pretty self-explanatory but many are not. I'd prefer to not have to read through all the code to decipher this.

Also, it would be enormously helpful to have a working example of a settings file that has working values in it.

Thanks.

**Comment by kwunyeung** [comment]
Does the `default_settings.json` help?

**Comment by njmurarka** [comment]
@kwunyeung Yes and no. The default settings file is not literally a working version of this file. For example, there is no example of what the genesisFile "address" is supposed to look like. I suspect it is an https:// url now. 

Also, even though some fields are filled in (most, in fact), I don't really understand what many of them mean. Granted, it could be that they are obvious to Cosmos experts. I am not an expert yet. As an example, I don't know what "powerReduction" and "coingeckoId" refer to. There are many others. 

Would love to get this up and running soon!

I will attach my own copy of the settings file here, named bluzelle.txt.

Thanks!

[bluzelle.txt](https://github.com/forbole/big_dipper/files/4170066/bluzelle.txt)

**Comment by kwunyeung** [comment]
@njmurarka the `gtm` is the Google Tag Manager. You can put it as false if you don't use it.
 
`powerReduction` is the term inside Cosmos SDK Staking module that reduce the token numbers into voting power. It was there to cater a special case in another project `LikeChain` where they have another power reduction than the default 1,000,000. Please put false there and this value will be ignored. In fact, the `stakingFraction` should be refactored as `powerReduction` for a better naming. 

The `coingeckoId` is for getting token price from [Coingecko](https://www.coingecko.com/) API. The default here set to `cosmos` as coin id of `ATOM` on Coingecko is `cosmos`. You can set it to false if you don't have the coin listed on Coingecko.

**Comment by njmurarka** [comment]
Cool -- thanks so very much for this!

I do recommend though having a "real" sample of the settings file that is included in the repo with every value filled in. 

I know this is work in progress, so apologies if I appear to be nagging. I just think it is a beautiful product and would love to see people being able to use it very easily. Having the annotations above in the docs would be great! Perhaps have them as comments in the settings JSON file?

**Comment by kwunyeung** [comment]
@njmurarka should the issues you created be closed?

**Comment by njmurarka** [comment]
Yep. Please close. 

For some reason, btw, my token (BLZ) is not showing anymore for CoinGecko. This used to work.
