### ISSUE TITLE
Using with my own chain... getting phantom validators and NaN in many places.

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#272]
Hi.

I was able to partially get Big Dipper running. It seems to have the right block height and even lets me explore blocks, TX's, etc. I only have ONE validator for now -- it is a test environment.

But I noticed that there is also much wrong with my setup. Clearly I missed something or messed something up.

Here are some of the issues I would love to get help on:

- When I look at either the random validator or active validator view, I see not just my validator (moniker Bluzelle) but also a bunch of others like node0, node1, etc. No idea where that is coming from!

- I see "NaN" all over the place. Like for the block height, but also many other places like the online voting power, 

- In the top right, I am seeing the price and market cap, etc, for ATOM. How do I change this?

- Overall, how do I configure the color scheme, etc?

I have attached a screen shot.

Much appreciated.

<img width="1653" alt="Screen Shot 2020-02-05 at 4 12 59 PM" src="https://user-images.githubusercontent.com/471362/73894824-81b66380-4832-11ea-8d0a-9e8534397907.png">

**Comment by kwunyeung** [comment]
If it reads your `RPC` and `LCD` correctly, the Latest block height should not be `NaN` and the number of validators should be shown. Primary colour can be changed in the `SCSS` file. There is a variable in the `SCSS`. Look for `coingeckoId` in the `settings.json`

**Comment by njmurarka** [comment]
@kwunyeung I am guessing based on all this that my RPC and LCD are not being read correctly. No idea why. Everything is local on the same machine. Thoughts? 

You can try it live at:

http://54.169.4.17:3000/

Thanks!

[bluzelle.txt](https://github.com/forbole/big_dipper/files/4170095/bluzelle.txt)

**Comment by kwunyeung** [comment]
Which version of Cosmos SDK are you using? May I also access to your RPC and LCD?

**Comment by njmurarka** [comment]
Hi.

Here is what I found the folder to be named:

cosmos-sdk@v0.37.4

Does this help?

**Comment by njmurarka** [comment]
I do not see these errors anymore with the latest version.
