### ISSUE TITLE
General issues on startup of Big Dipper server. CHECK SETTINGS JSON: genesisFile.33 is missing from settings and 404 errors

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#273]
Hi.

Apologies for the many tickets I added in a short time span. I spent a fair bit of time accumulating the issues I have before I posted them.

I am able to get Big Dipper running, but with several issues. I documented these in some other tickets. One of the things I noticed was some less-than-ideal-looking output when I start the process. I have placed it below.  In short, I get what seems like a bunch of errors with my genesis file, as well as repeated cycles of 404 errors for some resources that Big Dipper is trying to access.

Would appreciate any help.

Thanks.

=> Started proxy.                             
app/client/styles.scss: warn: There are some @import rules in the middle of a file. This might be a bug, as imports are only valid at the beginning of a file.
=> Started MongoDB.                           
W20200206-00:16:15.144(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.33 is missing from settings
W20200206-00:16:15.182(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.34 is missing from settings
W20200206-00:16:15.183(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.35 is missing from settings
W20200206-00:16:15.183(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.36 is missing from settings
W20200206-00:16:15.183(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.37 is missing from settings
W20200206-00:16:15.183(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.38 is missing from settings
W20200206-00:16:15.184(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.39 is missing from settings
W20200206-00:16:15.191(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.40 is missing from settings
W20200206-00:16:15.192(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.41 is missing from settings
W20200206-00:16:15.192(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.42 is missing from settings
W20200206-00:16:15.192(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.43 is missing from settings
W20200206-00:16:15.194(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.44 is missing from settings
W20200206-00:16:15.194(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.45 is missing from settings
W20200206-00:16:15.194(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.46 is missing from settings
W20200206-00:16:15.195(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.47 is missing from settings
W20200206-00:16:15.195(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.48 is missing from settings
W20200206-00:16:15.195(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.49 is missing from settings
W20200206-00:16:15.196(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.50 is missing from settings
W20200206-00:16:15.196(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.51 is missing from settings
W20200206-00:16:15.196(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.52 is missing from settings
W20200206-00:16:15.196(0)? (STDERR) CHECK SETTINGS JSON: genesisFile.53 is missing from settings
I20200206-00:16:15.213(0)? Genesis file has been processed
=> Started your app.

=> App running at: http://localhost:3000/
I20200206-00:16:20.219(0)? get proposals result: true
I20200206-00:16:20.223(0)? Error: failed [404] 404 page not found 
I20200206-00:16:20.223(0)?     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
I20200206-00:16:20.224(0)?     at Request._callback (packages/http.js:140:24)
I20200206-00:16:20.224(0)?     at Request.self.callback (/home/ubuntu/.meteor/packages/http/.1.4.2.bvcg5n.59c36++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:185:22)
I20200206-00:16:20.224(0)?     at Request.emit (events.js:210:5)
I20200206-00:16:20.224(0)?     at Request.EventEmitter.emit (domain.js:475:20)
I20200206-00:16:20.225(0)?     at Request.<anonymous> (/home/ubuntu/.meteor/packages/http/.1.4.2.bvcg5n.59c36++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1161:10)
I20200206-00:16:20.225(0)?     at Request.emit (events.js:210:5)
I20200206-00:16:20.225(0)?     at Request.EventEmitter.emit (domain.js:475:20)
I20200206-00:16:20.225(0)?     at IncomingMessage.<anonymous> (/home/ubuntu/.meteor/packages/http/.1.4.2.bvcg5n.59c36++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1083:12)
I20200206-00:16:20.226(0)?     at Object.onceWrapper (events.js:299:28)
I20200206-00:16:20.226(0)?     at IncomingMessage.emit (events.js:215:7)
I20200206-00:16:20.226(0)?     at IncomingMessage.EventEmitter.emit (domain.js:475:20)
I20200206-00:16:20.226(0)?     at endReadableNT (_stream_readable.js:1184:12)
I20200206-00:16:20.226(0)?     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
I20200206-00:16:20.226(0)?   response: {
I20200206-00:16:20.227(0)?     statusCode: 404,
I20200206-00:16:20.227(0)?     content: '404 page not found\n',
I20200206-00:16:20.227(0)?     headers: {
I20200206-00:16:20.227(0)?       'content-type': 'text/plain; charset=utf-8',
I20200206-00:16:20.227(0)?       'x-content-type-options': 'nosniff',
I20200206-00:16:20.227(0)?       'x-server-time': '1580948180',
I20200206-00:16:20.228(0)?       date: 'Thu, 06 Feb 2020 00:16:20 GMT',
I20200206-00:16:20.228(0)?       'content-length': '19',
I20200206-00:16:20.228(0)?       connection: 'close'
I20200206-00:16:20.228(0)?     },
I20200206-00:16:20.228(0)?     data: null
I20200206-00:16:20.228(0)?   }
I20200206-00:16:20.229(0)? }
I20200206-00:16:22.721(0)? updateStatus: no updates (getting block 21525 at block 302720)
I20200206-00:16:25.219(0)? get proposals result: true
I20200206-00:16:25.220(0)? Error: failed [404] 404 page not found 
I20200206-00:16:25.220(0)?     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
I20200206-00:16:25.220(0)?     at Request._callback (packages/http.js:140:24)
I20200206-00:16:25.220(0)?     at Request.self.callback (/home/ubuntu/.meteor/packages/http/.1.4.2.bvcg5n.59c36++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:185:22)
I20200206-00:16:25.221(0)?     at Request.emit (events.js:210:5)
I20200206-00:16:25.221(0)?     at Request.EventEmitter.emit (domain.js:475:20)
I20200206-00:16:25.221(0)?     at Request.<anonymous> (/home/ubuntu/.meteor/packages/http/.1.4.2.bvcg5n.59c36++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1161:10)
I20200206-00:16:25.221(0)?     at Request.emit (events.js:210:5)
I20200206-00:16:25.221(0)?     at Request.EventEmitter.emit (domain.js:475:20)
I20200206-00:16:25.221(0)?     at IncomingMessage.<anonymous> (/home/ubuntu/.meteor/packages/http/.1.4.2.bvcg5n.59c36++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/request/request.js:1083:12)
I20200206-00:16:25.222(0)?     at Object.onceWrapper (events.js:299:28)
I20200206-00:16:25.222(0)?     at IncomingMessage.emit (events.js:215:7)
I20200206-00:16:25.222(0)?     at IncomingMessage.EventEmitter.emit (domain.js:475:20)
I20200206-00:16:25.222(0)?     at endReadableNT (_stream_readable.js:1184:12)
I20200206-00:16:25.222(0)?     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
I20200206-00:16:25.222(0)?   response: {
I20200206-00:16:25.222(0)?     statusCode: 404,
I20200206-00:16:25.223(0)?     content: '404 page not found\n',
I20200206-00:16:25.223(0)?     headers: {
I20200206-00:16:25.223(0)?       'content-type': 'text/plain; charset=utf-8',
I20200206-00:16:25.223(0)?       'x-content-type-options': 'nosniff',
I20200206-00:16:25.223(0)?       'x-server-time': '1580948185',
I20200206-00:16:25.224(0)?       date: 'Thu, 06 Feb 2020 00:16:25 GMT',
I20200206-00:16:25.224(0)?       'content-length': '19',
I20200206-00:16:25.224(0)?       connection: 'close'
I20200206-00:16:25.224(0)?     },
I20200206-00:16:25.224(0)?     data: null
I20200206-00:16:25.224(0)?   }
I20200206-00:16:25.225(0)? }

**Comment by lacabra** [comment]
Hi @njmurarka, like you I am getting started with this block explorer, and the output of my installation matches yours.

I cannot find in the documentation what the LCD port is supposed to be. Have you found any information in this regard, because I believe the `404` errors above come from having that address:port misconfigured.

**Comment by njmurarka** [comment]
@lacabra I thought I actually got the LCD part right :). I am not certain but am guessing it is the light-client-daemon, also known as the rest-client that you initiate by starting the client with the "rest-server" directive. By default, that listens on 1317 and this is what you specify in the LCD section. 

Maybe :). I have so many errors so I could be wrong.

**Comment by kwunyeung** [comment]
@njmurarka Can you confirm if the `RPC` and `LCD` are working properly?

@lacabra `LCD` stands for Light Client Daemon. It's the old name for the [Cosmos SDK RESTful API](https://cosmos.network/rpc/).

**Comment by njmurarka** [comment]
@kwunyeung To be honest, I am not sure anymore I got the LCD working properly. Based on another question I had where I had all sorts of NaN messages everywhere, it might seem my LCD is not working. 

How do I actually know that the RPC and LCD are working properly? I am able to interact with them just fine outside of BigDipper (like for restful endpoints or with the CLI). 

I basically just pointed BigDipper at the RPC and LCD endpoints and assumed it was fine... but perhaps I did it wrong. 

I have attached my config file, renamed to "bluzelle.txt". In fact, you can also see within it a link to the genesis file for my Cosmos network. Perhaps something obvious?

Thanks.

[bluzelle.txt](https://github.com/forbole/big_dipper/files/4170035/bluzelle.txt)

**Comment by njmurarka** [comment]
I have been able to get Big Dipper working way better now with the latest release. I still do see these errors on startup.
