### ISSUE TITLE
Please support SDK v0.38.x (Tendermint-v0.33.0)

### ISSUE THREAD

**Issue by michaelfig** [forbole/big-dipper#284]
**Is your feature request related to a problem? Please describe.**
The Agoric chain is moving to tendermint-v0.30.0. It looks like big-dipper does not yet support the new commit format (no "precommits", just "signatures").

**Describe the solution you'd like**
Please see https://github.com/nomic-io/js-tendermint/issues/25 for the issues I found with a JS light client, and https://github.com/nomic-io/js-tendermint/pull/26 for how I solved it.

**Describe alternatives you've considered**
Not sure if these changes are the best, but at least are a direction to explore.

**Additional context**
No other details.

**Comment by michaelfig** [comment]
The https://github.com/forbole/big-dipper/tree/kwun/tendermint-v.0.33 branch doesn't appear to display validators.  You can see it in action at [the Agoric Testnet explorer](https://explorer-testnet.agoric.com).

**Comment by kwunyeung** [comment]
Please post any error messages you see. Thanks!

**Comment by kwunyeung** [comment]
The branch is now renamed to `kwun/sdk-v0.38.x`.

**Comment by michaelfig** [comment]
I'm actually on cosmos-sdk's ibc-alpha branch.  That's due to become part of SDK v0.39.0.

I'll try rerunning a big-dipper from scratch.  The current one's start date has passed by enough that I can't really see the root cause for the errors, it's long before the minting  404's I'm getting.

I'll post again when I can capture the errors.

**Comment by michaelfig** [comment]
I've opened #310 with the error details.

**Comment by michaelfig** [comment]
#311 is the actual error (closed #310 due to my own human error).
