### ISSUE TITLE
New validators that use seck256p1 signatures not showing up

### ISSUE THREAD

**Issue by sorawit** [forbole/big-dipper#288]
**Describe the bug**
We are running a testnet for [Band Protocol](https://bandprotocol.com). The explorer endpoint is available here: http://band-wenchang-testnet1.bandchain.org:12000/. As you can see below in screenshots, on the front page there are 5 validators, but when you go to the "validators" tab, only 1 is shown.

The 1 validator that is shown is a validator since the block genesis (in genesis.json file). The other 4 were added later with `MsgCreateValidator`. All validators use `seck256p1` signatures. 

Upon close inspection, I found that "no con pub key?" (https://github.com/forbole/big-dipper/blob/master/imports/api/blocks/server/methods.js#L458) log is fired repeatedly. This is because it cannot match conspubkey with different prefixes. For example, when `valExist.consensus_pubkey` is `bandvalconspub1zcjduepqq2sq54888808mez7rhnsx7sj6fekukjwrpfgj850z98l667qgklsvpnp8d`. The matching key in `validatorSet` likely is `bandvalconspub1addwnpepq2sq54888808mez7rhnsx7sj6fekukjwrpfgj850z98l667qgklsxyqj20v`. If you notice, it is the exact same pubkey but with different prefix. So the dictionary lookup fails.

I also noticed that in many places in the codebase, it assumes `ed25519` signatures. This should not be the case since Tendermint also natively supports `seck256p1`? Example: https://github.com/forbole/big-dipper/blob/master/imports/startup/server/util.js#L18.

**Expected behavior**
All validators should be shown properly.

**Screenshots**

![Screen Shot 2020-02-21 at 10 16 17](https://user-images.githubusercontent.com/5730246/75001168-3c7d6d00-5493-11ea-9f7e-5ce16077c229.png) 

![Screen Shot 2020-02-21 at 10 17 04](https://user-images.githubusercontent.com/5730246/75001215-561eb480-5493-11ea-9400-9feba5a3f67c.png)

**Comment by kwunyeung** [comment]
@sorawit Thank you for the report! Yes currently on the default `ed25519` validator private key is supported. We do know that the validator private key type can be changed in the genesis file and this is a great suggestion to add support for `secp56k1`. Are you guys working on Bitcoin peg zone? I would like to see the priority of this feature.
