### ISSUE TITLE
I get a NaN for inflation if I don't have minting turned on

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#293]
**Describe the bug**
If I do not have minting turned on in my genesis.json file for my chain, inflation shows as NaN in the BigDipper app.

**To Reproduce**
Turn off inflation and start the chain
Observe the inflation display

**Expected behavior**
Inflation should be 0 or just not show

**Screenshots**
See screenshot
<img width="749" alt="Screen Shot 2020-02-27 at 4 00 23 AM" src="https://user-images.githubusercontent.com/471362/75443182-b9866780-5915-11ea-8bb5-7643734665c1.png">

**Comment by kwunyeung** [comment]
Yeah, we didn't handle that properly. Thanks for creating this issue. We are going to remove reading genesis file and move all parameters reading on chain on the fly.

**Comment by kwunyeung** [comment]
Tracked in #429
