### ISSUE TITLE
How do I reset "state"

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#299]
I am trying to use an install I had of Big Dipper that I had talking to another chain instance. I have now replaced that chain instance with another, but Big Dipper seems to still think it is talking to that old chain. For example, it is look for blocks in the area of block #95,000 when this new chain is under 1,000 still. 

Is there some db or files I need to reset here?

Update:

I deleted the ".meteor/local/db" folder and that seemed to have kind of worked. But I am not sure if this is the right thing to do. I also happened to update my chain to the Cosmos-SDK 0.38.1. 

Right now I am seeing that my validators and blocks are not showing up.

**Comment by kwunyeung** [comment]
If you start it with `Meteor`, then you can do a `meteor reset` and it will swipe the database. You may refer to [the documentation of the `meteor` command line](https://docs.meteor.com/commandline.html#meteorreset).

Please try out [this branch](/forbole/big-dipper/tree/kwun/tendermint-v0.33) for `SDK v0.38.1`.

**Comment by kwunyeung** [comment]
@njmurarka is your question answered? May I close this issue?

**Comment by neeraj-bluzelle** [comment]
Yes. Thank you. Please close.
