### ISSUE TITLE
If minting is not on or not enabled, console keeps giving failed 404

### ISSUE THREAD

**Issue by neeraj-bluzelle** [forbole/big-dipper#319]
I see repeated ongoing attempts to access:

**Comment by kwunyeung** [comment]
Thanks for reporting. We are going to separate them in modules and can be enabled in the settings. It's being tracked with #305 .

**Comment by neeraj-bluzelle** [comment]
I accidentally clicked submit for this before I was done. Sorry. Please delete this one.
