### ISSUE TITLE
Constant 404's related to minting/annual-provisions

### ISSUE THREAD

**Issue by neeraj-bluzelle** [forbole/big-dipper#320]
I see repeated ongoing attempts to access the following on the console:

http://...:1317/minting/annual-provisions

I suspect this is because I do not have minting turned on. But I should not have to have it on.

Maybe a config parameter, or something? Would be nice to have this removed from the console output so it is "cleaner"?

**Comment by kwunyeung** [comment]
I think this is the same issue as #319 ?

**Comment by kwunyeung** [comment]
Close as duplicates
