### ISSUE TITLE
Staking support in SDK 0.38

### ISSUE THREAD

**Issue by steevi** [forbole/big-dipper#326]
**Describe the bug**
Staking support seems not to be working. I'm using SDK 0.38.1.

I do not have a problem to stake with big-dipper `master` branch and SDK 0.37.6

**To Reproduce**
Merged `agoric-labs:validatorStatus0` into `forbole:kwun/sdk-v0.38.x`. 
Transfer stake to my ledger account
Logged in to ledger via big-dipper
Opened validator, and clicked delegate
Received error `Cannot read property '0' of undefined`

**Comment by kwunyeung** [comment]
Thanks for reporting.

**Comment by Cashmaney** [comment]
Not sure where you guys are on this, but I'm working with big-dipper on sdk 0.38.3 - took me a few changes, which you can see [on my fork](https://github.com/Cashmaney/big-dipper). Feel free to take a look if you didn't get around to it yet

**Comment by steevi** [comment]
Do you know if staking is working?

**Comment by Cashmaney** [comment]
Delegating is working. Looking at it I found a bug with withdrawing rewards though, so I'll have to take a look at that

**Comment by kwunyeung** [comment]
Thanks @Cashmaney ! We have a PR for that issue but haven't organize all of them yet.

**Comment by steevi** [comment]
Just tested it yesterday! Works perfect!
