### ISSUE TITLE
Remove the value estimation if the token value cannot be fetched

### ISSUE THREAD

**Issue by RiccardoM** [forbole/big-dipper#347]
**Is your feature request related to a problem? Please describe.**
Currently when it's not possible to fetch the price of a token, the displayed value is `$NaN` (which I suppose to be the result of the operation `amount/price` if `price == 0`). 

**Describe the solution you'd like**
I think the best way to handle this is to not display the estimation of the token value if the price is zero, to avoid this unaesthetic value. 

**Describe alternatives you've considered**
A solution might be to simply show an estimation of `$0.00`

**Additional context**
![screenshot-morpheus desmos network-2020 05 13-12_44_03](https://user-images.githubusercontent.com/9119016/81803376-e52dec80-9517-11ea-8542-4cc07a445f46.png)

**Comment by kwunyeung** [comment]
Should have fixed.
