### ISSUE TITLE
Transaction hash is not fully visible if browser has reduced width

### ISSUE THREAD

**Issue by RiccardoM** [forbole/big-dipper#348]
**Describe the bug**
Inside the transactions details, the transaction hash cannot be properly displayed if the browser has a reduced width. In my case I've got a 1920*1080 screen and set BigDipper to have a 50% width (540 pixels).

**To Reproduce**
1. Set the browser to have a 50% width of your screen. 
2. Go into any transaction details page.
3. Look at the hash.

**Expected behavior**
The hash should be fully visible no matter the width of the browser window.

Two possible solutions to achieve this might be: 

1. Reduce the size of the hash text. 
2. Put the hash text below the **Hash** title so have more space.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
![screenshot-morpheus desmos network-2020 05 13-12_49_37](https://user-images.githubusercontent.com/9119016/81804005-c3813500-9518-11ea-9526-fd47813aed83.png)

**Comment by kwunyeung** [comment]
I'm going to cherry pick the commit 629d2776e05a49665cd799e6f7153d54d8559e6a.

**Comment by kwunyeung** [comment]
Should have fixed.
