### ISSUE TITLE
kwun/sdk-v0.38.x: Bundling for production is failing with many errors

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#349]
I unbundled the tarball and followed the directions in the README.

I know my MONGO_URL is correct since I used its value, verbatim, to connect to MongoDB locally. 

When I ran the software, I get the following:

```
node main.js 
/home/ubuntu/src/output/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'find' of undefined
    at module (both/utils/coins.js:28:32)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /home/ubuntu/src/output/bundle/programs/server/app/app.js:4911:1
    at /home/ubuntu/src/output/bundle/programs/server/boot.js:398:38
    at Array.forEach (<anonymous>)
    at /home/ubuntu/src/output/bundle/programs/server/boot.js:226:21
    at /home/ubuntu/src/output/bundle/programs/server/boot.js:461:7
    at Function.run (/home/ubuntu/src/output/bundle/programs/server/profile.js:280:14)
    at /home/ubuntu/src/output/bundle/programs/server/boot.js:460:13
```

Please help. Very stuck here.

**Comment by kwunyeung** [comment]
Hi @njmurarka! Are you following the [Meteor deployment guide](https://guide.meteor.com/deployment.html#custom-deployment) to deploy the Big Dipper in production? Also please set the environment variables correctly. One that you may have missed is the [`METEOR_SETTINGS`](https://docs.meteor.com/environment-variables.html#METEOR-SETTINGS) which holds the `settings.json`.

**Comment by w3care** [comment]
@kwunyeung , can you please let me know command to run the production build?

I have tried going to root directory of build and then ran 
1. node main.js 
2. pm2 start main.js

Also, please let me know the default port that listens this?

Thanks

**Comment by kwunyeung** [comment]
@w3care PM2 should work. For mongodb, you may want to install the community edition. https://docs.mongodb.com/manual/administration/install-on-linux/

**Comment by w3care** [comment]
Hello @kwunyeung ,

Thanks for your reply. Actually, in the project https://github.com/forbole/big-dipper we are not using mongodb so but are using remote "rpc" and "lcd" in development. So, wanted to ask if we still need to use mongodb in production? Please let me know if using mongodb and mongodb url is required for production deploy. Also, please let me know what will be collections for mongodb database in case we need to use it.

Thanks

**Comment by kwunyeung** [comment]
@w3care sorry for the late reply. Yes we use MongoDB to index the blocks to give a better web UX.
