### ISSUE TITLE
All precommits cannot be catched after deploying the v0.38.x branch

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#350]
This happens on Kava testnet after the using the v0.38.x branch. Kava is still not using the latest SDK 0.38. We have to refactor this.

![image](https://user-images.githubusercontent.com/932636/81934667-e9dec780-9621-11ea-9264-28d76839ced2.png)

**Comment by MonikaCat** [comment]
Fixed in commit `0570a93`
