### ISSUE TITLE
TypeError: require(...).enable is not a function

### ISSUE THREAD

**Issue by w3care** [forbole/big-dipper#354]
I am getting this error when running production build:

/home/ubuntu/bundle/programs/server/node_modules/fibers/fibers.js:90
                                        return fn.apply(this, arguments);
                                                  ^

TypeError: require(...).enable is not a function
    at module (packages/modules.js:187:30)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)

I am running this command:-

METEOR_SETTINGS='{
    "public":{
    }
}' MONGO_URL=mongodb://mysite.com/myapp  ROOT_URL=http://mysite.com:3000 node main.js

Please let me know what I am missing.

**Comment by kwunyeung** [comment]
@w3care have you followed the deployment guide from Meteor? https://guide.meteor.com/deployment.html#custom-deployment

**Comment by kwunyeung** [comment]
@w3care did you solve it?
