### ISSUE TITLE
Distribution transactions are not shown on validator page

### ISSUE THREAD

**Issue by svantetobias** [forbole/big-dipper#358]
**Describe the bug**
Distribution transactions are not shown for the validator cosmosvaloper1gdg6qqe5a3u483unqlqsnullja23g0xvqkxtk0

**To Reproduce**
1. Go to https://cosmos.bigdipper.live/validator/cosmosvaloper1gdg6qqe5a3u483unqlqsnullja23g0xvqkxtk0/transactions
2. Click on Distribution
3. See error "We're sorry - something's gone wrong. Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue."

**Expected behavior**
To see the list of validator distribution transactions

**Screenshots**
![image](https://user-images.githubusercontent.com/1716817/82928170-25628580-9f82-11ea-86f5-b710b08de24d.png)

**Comment by kwunyeung** [comment]
@svantetobias thank you for the bug report!
