### ISSUE TITLE
Active validators seems to not be reported consistently

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#360]
**Describe the bug**
My understanding is that in Tendermint-speak, there are validators, and all validators are either active or candidates/proposed. 

Since there is a limit on how many validators are allowed to participate in consensus (say 100), you could very likely have a situation with 180 total validators, of which 100 are active and 80 are candidates/proposed. 

Here is the URL to my install of Big Dipper:
```
http://explorer.testnet.public.bluzelle.com:3000/
```
At the time of this writing, it says "Active Validators 100 out of 182 validators"

Screenshot:
![Screen Shot 2020-05-31 at 12 12 02 AM](https://user-images.githubusercontent.com/471362/83346725-e1e67f00-a2d3-11ea-9b8b-03522defb3ce.png)

But here is the actual "Active Validators" page:
```
http://explorer.testnet.public.bluzelle.com:3000/validators
```
It shows 149 validators in this list.

Screenshot:
![Screen Shot 2020-05-31 at 12 16 53 AM](https://user-images.githubusercontent.com/471362/83346748-12c6b400-a2d4-11ea-8e4d-0324bcf1e120.png)

So here is the confusion:

- The main page shows (perhaps correctly) that I have 100 active validators and a total of 182 validators. So I infer then that i have 82 candidate/proposed validators. 
- The "active validators" page shows a whole other number... a total of 147 "active" validators.

To make this even more bizarre (this part I believe is me not understanding Cosmos or Tendermint sufficiently), I have configured (in my genesis.json) to have 250 max validators. Here is a URL to get my genesis.json:
```
http://testnet.public.bluzelle.com:1317/genesis.json
```

Screenshot:
![Screen Shot 2020-05-31 at 12 28 35 AM](https://user-images.githubusercontent.com/471362/83346924-b795c100-a2d5-11ea-8480-ae8bb5ecc5e4.png)

So I am probably not setting the actual max # of validators correctly (I want 250 to be the max number of ACTIVE validators). Regardless, I am confused by the output I see in my Big Dipper instance.

**To Reproduce**
Included above in "Describe the bug"

**Expected behavior**
Included above in "Describe the bug"

**Screenshots**
Included above in "Describe the bug"

**Comment by kwunyeung** [comment]
Yes this is know bug and have been fixed in a commit. It will be available in the next release.

**Comment by njmurarka** [comment]
Thanks for the clarification. 

Could you let me know please which part is the bug, so I can tell my community? For example, is it the actual list of validators that should not be listing more than 100 active? Or something else? Please clarify.

Much appreciated.

**Comment by kwunyeung** [comment]
It's about how the validator set is being saved.

https://github.com/forbole/big-dipper/commit/01a1eb2f26a48bc25a5a6e7028e46132c4bdac58#diff-cde1506c7965dcf09ab180c8da631843R186

The original code was very old which during the testnet of Cosmos Hub there were no case with unbonding validator have less than 1 voting power. The original code verify with the validator set and the validator list before saving to the database. The commit above save the validator list directly without verifying with the validator set.

**Comment by njmurarka** [comment]
Can you merge this into the 0.38.1 branch?

**Comment by kwunyeung** [comment]
We will be doing that soon.

**Comment by njmurarka** [comment]
Understood. Any idea when? I apologize for pushing but BD consistently
starts to show "erratic" results once we pass 100 validators... we are at
101 now and it is quite inconsistent.

Much appreciated.
