### ISSUE TITLE
What is the uptime based on? 

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#362]
Hello and thanks again for the fantastic work.

We are running a validator competition and want to use the uptime reported from Big Dipper as a key metric in placing winners.

We have also set the "uptimeWindow" value in the "public" section of the settings file to 500,000, which should be more than enough of a window to provide accuracy for the timespan of the competition.

Our URL:
```
http://explorer.testnet.public.bluzelle.com:3000/
```

We have some questions about the uptime. 

- We have many more validators than we have lots for active validators. What I mean is, we are currently limited (a separate issue) to 100 active validators. But we have over 180 validators that have staked and are running validating nodes. Does uptime get affected in any way by the time you are in the active validator set, vs not being in it? For example, if node A and node B were both "up" 100% of the time but node B was only active for 50% of that time while A was active 100%, would A's uptime be double that of B's? It is super critical for us to know if we can count on the uptime as a fair metric for everyone, regardless of their active validator status. 

- Less important but does uptime get affected by the "startHeight" in the "params" section of the settings file? I noticed that if I set the startHeight to something non-zero, all the validators start at a pretty low uptime... are they implicitly being "punished" for the blocks that are "skipped" as if these nodes were down that whole time?

Thanks.

**Comment by kwunyeung** [comment]
1. Uptime is only available for active validators and it's calculated with the latest number of blocks defined in `uptimeWindow`. This will be changed in the next version.
2. `startHeight` is for controlling which height Big Dipper will start indexing.

**Comment by njmurarka** [comment]
> 1. Uptime is only available for active validators and it's calculated with the latest number of blocks defined in `uptimeWindow`. This will be changed in the next version.
> 2. `startHeight` is for controlling which height Big Dipper will start indexing.

Thanks for the quick reply.

1. So if some of our validators are not active, they will actually get a lower uptime than validators that are active, even of all these validators are actually "running" (daemon running, healthy, etc)? I think you answered my question, but can you confirm then, that uptime is not an accurate metric then for establishing the uptime of both active and candidate validators?

2. So if we were on block 100 right now and startHeight was 50, would that mean that all the validators would start off with an uptime of only 50%? I am pretty sure this is what I noticed. 

BTW, we are using the "kwun/sdk-v0.38.x" branch.

**Comment by kwunyeung** [comment]
Uptime is about whether a validator is voting precommit  (2nd signature of the previous block) at a certain block. If the validator miss voting that block, it's not considered up even if the daemon is running.

**Comment by njmurarka** [comment]
If I may ask, where do you get this information? Which API call?

Thanks.

**Comment by kwunyeung** [comment]
The signatures can be read from the blocks. You can read them directly from Tendermint RPC.

**Comment by njmurarka** [comment]
Thanks. Do you mean the call to "blzcli q block <N>"?

**Comment by kwunyeung** [comment]
@njmurarka you can read the signatures from the Tendermint RPC `/block` endpoint.

https://docs.tendermint.com/master/rpc/#/Info/block
