### ISSUE TITLE
Create Bep3 BNB swap from Binance to Kava

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#363]
### Problem

Looks like there will be no easy way for users to create bep3 claim from Binance directly. If the users create bep3 swap from other wallets like Frontier and Cosmostation, they will not be using Ledger to do so. We better have our own solution for this.

### Solution

We can create a user flow which the user input required information and a swap will be initiated. It works like a separate tool rather than using the Ledger directly.

1. Save `Kava`, `Binance` deputy accounts, `Binance` endpoint in the `settings.json`
2. After user login with Ledger, a `BNB Swap` button is shown
3. We get the address from the `LocalStorage` and this is the receive address on `Kava`
4. The user needs to input 
    - address on `Binance`
    - seed phrase of the account
5. Warn the user that we nothing will be stored on our server
6. Send the request to `Binance` endpoint
7. Display the random number hash and swap id
8. Initiate the claim

**Comment by gr8scott06** [comment]
Items 5 & 6 do present a solution, however we might expect the user submits a seed phrase whose account balance is low. Consider the Ledger user segment often has higher balances, so this solution only works for a subset of that segment.

**Comment by kwunyeung** [comment]
@gr8scott06 as mentioned before, we have built this solution 

https://github.com/forbole/big-dipper/blob/monika/kava-testnet/imports/ui/bep3/CreateSwapButton.jsx#L198

but seems not quite fit the whole ideology behind using Ledger on Big Dipper and we haven't deployed it.
