### ISSUE TITLE
how to use put the setting.json for production use

### ISSUE THREAD

**Issue by jjhesk** [forbole/big-dipper#364]
There is a missing setting.json when starting the production daemon node 

what is the correct path to put the setting file?

**Comment by kwunyeung** [comment]
@jjhesk you can refer to this page on how to deploy a meteor application with settings in the environment variable

https://docs.meteor.com/environment-variables.html#METEOR-SETTINGS

**Comment by jjhesk** [comment]
Thank you so much.. @kwunyeung
