### ISSUE TITLE
Transaction list keeps falling behind

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#366]
I have noticed (in my chain with 180+ validators) that the transaction tab is lagging. Sometimes, it is behind by 1-2 days or just hours, but it often cannot "keep up" with what is going on right now.

Any idea?

I am using the 0.38.1 branch.

**Comment by kwunyeung** [comment]
Big Dipper indexes all blocks and transactions. You may not have enough resources to index the blocks in time.

**Comment by njmurarka** [comment]
Indeed that is possible but I am not sure what I need to do then to
resolve this.

I specifically setup an instance on AWS with the following config:

32 GB RAM, 8 vCPUs, 640 GB SSD

I expected this would be overkill, but I am still getting this problem. Is
there something I need to do here to properly use these resources? I am
running a production instance.

**Comment by kwunyeung** [comment]
Wow, you should have enough resources to run.

**Comment by njmurarka** [comment]
Yes... which is why I do not know what I can do about it now...

**Comment by njmurarka** [comment]
Any thoughts on why the transactions are falling behind? Is it related to
the other issue regarding high # of validators?

**Comment by kwunyeung** [comment]
@njmurarka are the blocks being processed up-to-date? How many transactions are in the blocks? We had over 230 validators during Game of Stakes and Big Dipper ran properly.

**Comment by njmurarka** [comment]
There are at most 1-2 transactions in each block. 

I am not sure what you mean by "are the blocks processed up-to-date"? That is the actual problem -- when I go and look at the transactions screen, it is lagging behind by hours and sometimes longer. 

http://explorer.testnet.public.bluzelle.com/transactions

I am not saying it is the # of validators -- there is indeed a different issue I filed where BD is not reporting the right info on validators, that you are already familiar with.

But this is the issue that TX's are lagging way behind. 

We are on Cosmos 0.38.5 and so we are using BD's 0.38.x branch. 

Please help ASAP. I have tried everything I possibly can to resolve this including ensuring the BD node is sitting in the same data center as the node it syncs with and throwing an obscene amount of resources (CPU, etc) at the BD machine, but it still keeps falling behind like this.

Please tell me what info you need so we can resolve this. Thanks.

**Comment by kwunyeung** [comment]
It's pretty strange. Your BD is running pretty slow. Can you restart it and see if it helps? Also try restarting the node and the rest server.

**Comment by njmurarka** [comment]
I do restart it every few days. 

If I do that, it takes 24-48 hrs and then BD "catches up". Then, after a few days, it falls behind again, until I again restart it.

Can't easily restart the node and rest server in my current setup as BD is connecting to a round-robin DNS of many nodes and REST servers for the purpose of redundancy and load balancing. And all these nodes are up and operational. 

That having been said, I don't know what to do at this point. Not sure where the problem lies. Not saying the problem is in BD, of course.

**Comment by kwunyeung** [comment]
I don't get it. You mentioned that you are running production build, why it takes 2 days to catch up? How do you restart BD?

**Comment by njmurarka** [comment]
When I say restart, I do not mean that I stop and reset the DB state of BD and then start it again. I mean that I stop the process and start it again. The "catching up" refers to BD displaying TX's in the TX tab that are current. As mentioned, it "falls behind" regularly and the only way to get it to catch up is to stop and start it again (not reset and restart) and then wait a day or so. 

Right now, for example, it is showing TX's that happened 20 hrs ago. If I stop BD now and immediately start it again, it will slowly "catchup" and then eventually fall behind again.

I honestly have no idea what to do at this point.

Would appreciate any help. I am on Cosmos 0.38.5 now, but this problem was occurring with 0.38.x in general. 

![Screen Shot 2020-07-20 at 12 28 46](https://user-images.githubusercontent.com/471362/87978206-e255f780-ca84-11ea-9407-ead3a71ff56b.png)

**Comment by kwunyeung** [comment]
I really don't have any idea. BD of Akash, Kava, Desmos are running with this branch and I don't see a problem like this. We had a lag of processing in Akash once as there were 5000 txs in nearly every block.

**Comment by njmurarka** [comment]
Is there any logs I can email to you? Diagnostics? Could I give you access to one of our boxes to login yourself to look at it? I have no idea either of course, but I think that if you directly looked at it, you might get insight.

**Comment by njmurarka** [comment]
Also I noted a new branch cherry-pick-v0.38-fixes but also that the 0.38.x branch is gone (maybe I missed it). Any changes there?

**Comment by kwunyeung** [comment]
The `v0.38.x` branch is merged to `master`. We are trying to cherry pick some commits we have done for other projects back in `master`.
