### ISSUE TITLE
The account page for some accounts doesn't load 

### ISSUE THREAD

**Issue by MonikaCat** [forbole/big-dipper#375]
**Describe the bug**
The account page doesn't load for some accounts that have a commission 

**Screenshots**
![Screenshot 2020-07-14 at 4 21 37 PM](https://user-images.githubusercontent.com/37407870/87402585-5bb99a00-c5ee-11ea-890e-5819f6c83279.png)

**Comment by kwunyeung** [comment]
fixed in #376
