### ISSUE TITLE
Allow undelegations for all decimal amounts

### ISSUE THREAD

**Issue by housemobile** [forbole/big-dipper#378]
I have  0.000000635932095321469 as dust delegated to a validator. I'd like to undelegate it so it stops showing up but Big Dipper only lets me transact up to 6 decimal places. Please increase this to 21 (or whatever the maximum amount of decimals in Cosmos is) so I can undelegate the full amount. Thank you.

**Comment by kwunyeung** [comment]
Hi @housemobile ! Thank you for reporting issue. However, this is currently not possible as the undelegation message on `Cosmos Hub` only accept an amount of `uatom` which is 6 decimal places of `ATOM`.

https://github.com/cosmos/cosmos-sdk/blob/v0.37.13/x/staking/types/msg.go#L318

**Comment by kwunyeung** [comment]
It's a feature in the SDK. Can't be fixed.
