### ISSUE TITLE
likecoin.bigdipper.live - unable to redelegate

### ISSUE THREAD

**Issue by ckxpress** [forbole/big-dipper#398]
**Describe the bug**
after clicking the redelegate button on the validator page, it shows "We're sorry - something's gone wrong. Please try to refresh the page and see if the problem is gone.". retried a few times over a few hours.

**To Reproduce**
1. login https://likecoin.bigdipper.live with ledger. check own wallet.

2. go:
https://likecoin.bigdipper.live/validator/2C021179E6F72C87943883CFB64F4E114A23E487
(or the validator which you delegated LikeCoin)

3. hit "redelegate"

4. We're sorry...

**Expected behavior**
choose validators to redelegate to 

**Screenshots**
![Screen Shot 2020-09-03 at 6 28 01 PM](https://user-images.githubusercontent.com/7088918/92103995-4b19e900-ee13-11ea-890c-3fa85ecf2158.png)

**Desktop (please complete the following information):**
 - Mac OS 10.15.6 on Mac mini
 - Chrome 85.0.4183.83
 - also Brave 1.13.82

**Comment by kwunyeung** [comment]
Fixed in the latest #b715b48 commit in likechain branch.
