### ISSUE TITLE
News ticker

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#40]
Need to gather news sources. Twitter? Any specific blogs? Collaborate with CoInsight?

**Comment by clawmvp** [comment]
I think it should be a curated list, to avoid the noise.

**Comment by kwunyeung** [comment]
> I think it should be a curated list, to avoid the noise.

How do you think this should be filtered and define as noise?

**Comment by clawmvp** [comment]
I would use one of the newsletters like the one from lunamint, i would not
use a twitter hashtag.

**Comment by kwunyeung** [comment]
It will be in the v2. Closing for now.
