### ISSUE TITLE
Stargate 3a explorer shows Error on transaction

### ISSUE THREAD

**Issue by taariq** [forbole/big-dipper#402]
**Describe the bug**
https://stargate.bigdipper.live/transactions shows error
```sdk: failed to execute message; message index: 0: 0muon is smaller than 9muon: insufficient funds```

**To Reproduce**
1. Go to 'https://stargate.bigdipper.live/transactions/8DD4A18B61A018DCCC9E9B6C3FC779F9CDD556A8B266B1AB6409AFE09351F99E'
'We're sorry - something's gone wrong.'

**Expected behavior**
Transaction should be returned.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS
 - Browser Firefox
 - Version 81

**Comment by kwunyeung** [comment]
@taariq for the first error you mentioned, it's because you don't have enough tokens to process the transaction. For the error of the page, it's due to we still need to rewrite some components for the new structure of the txs.

**Comment by taariq** [comment]
Awesome! Thank you! We can close this issue then
