### ISSUE TITLE
improve initial sync time

### ISSUE THREAD

**Issue by vincentgeneste** [forbole/big-dipper#405]
Hi!

I'm using Big Dipper on a cosmos chain with very low block time (1-2 sec) and I can't figure out how to speed up the initial sync. Based on my calculations it will take currently 10 days for me to sync-up, with a chain relatively young.

Any way to fasten this up? Is that purely based on RPC calls? Does disk speed matter? any settings I can tweak? or maybe use multiple RPC at same time?

Cheers

**Comment by kwunyeung** [comment]
Hi @vincentgeneste ! Currently there is no way to sync data with multiple RPCs. To increase performance, make sure you are running the application in production build. The whole stack is Mongo, Node.js, React application. You may study which part can you increase the performance. It queries from the fullnode so the performance of the is also related.

**Comment by vincentgeneste** [comment]
Thanks a lot, will investigate all that!

**Comment by kwunyeung** [comment]
We are maintaining another project [BDJuno](https://github.com/forbole/bdjuno). It will be the backbone of the next version of Big Dipper. It separate the block indexing and data processing from different modules using subscriptions. You may take a look if you are interested.
