### ISSUE TITLE
「likechain」account page is failed to load

### ISSUE THREAD

**Issue by guanyun-helo** [forbole/big-dipper#412]
**Describe the bug**
https://likecoin.bigdipper.live/account/cosmos1mztweu8y2lazpapfgtqmadxaqaapyasvmqa947
account page is failed to load

**To Reproduce**
1. Click on 'https://likecoin.bigdipper.live/account/cosmos1mztweu8y2lazpapfgtqmadxaqaapyasvmqa947'
2. Error file is https://github.com/forbole/big-dipper/blob/d506f71c6003fb6ded2a668d35dc87ff7ee5304f/imports/ui/accounts/Account.jsx

**Comment by kwunyeung** [comment]
Thanks! Will fix this asap.

**Comment by guanyun-helo** [comment]
If you don't mind I would like to fix this problem. I wanner ask if big dipper dev could run on personal pc (windows)?

**Comment by guanyun-helo** [comment]
Copy default_settings.json to settings.json.
Update the RPC and LCD URLs.
Update Bech32 address prefixes.
Update genesis file location.

And for step 2-4 is there any detail ?

**Comment by kwunyeung** [comment]
Closes with #427
