### ISSUE TITLE
unable to go any validator page when logged in thru Ledger

### ISSUE THREAD

**Issue by ckxpress** [forbole/big-dipper#413]
**Describe the bug**
Unable to go any validator page when logged in thru Ledger. After logged out it resume to normal. Happens on kava & band.

**To Reproduce**
1. without log in. go to https://kava.bigdipper.live/validator/kavavaloper14kn0kk33szpwus9nh8n87fjel8djx0y02c7me3
2. log in thru your ledger
3. error - We're sorry - something's gone wrong. Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue.
4. log out and go to 1.

**Expected behavior**
can view regardless of login

**Screenshots**
![Screen Shot 2020-10-28 at 9 06 19 AM](https://user-images.githubusercontent.com/7088918/97378250-ddfb6f00-18fc-11eb-9417-c8ee2789ba46.png)

**Desktop (please complete the following information):**
 - macOS 10.15.7
 - Chrome Version 86.0.4240.111
 - Cosmos app 2.16.3 on ledger

**Comment by kwunyeung** [comment]
`chainStatus.staking.params` is missing.
