### ISSUE TITLE
Proposal page showing wrong tally result

### ISSUE THREAD

**Issue by nnkken** [forbole/big-dipper#426]
**Describe the bug**
Proposal 5 of LikeCoin chain was passed on 2020-11-10, with >40% quorum votes.

But the proposal page on BigDipper shows that `37.76% of online voting power has been voted. Less than 40.00% of voting power is voted. This proposal is invalid.`

https://likecoin.bigdipper.live/proposals/5

The `Proposal Status` field shows `Passed`, which is correct.

**Expected behavior**
The tally result should show the voting power and percentage value at the moment when the proposal is settled.

**Screenshots**
![image](https://user-images.githubusercontent.com/6733599/99497247-9a060200-29b0-11eb-8b9b-5bde9f5a49b5.png)
![image](https://user-images.githubusercontent.com/6733599/99497273-a2f6d380-29b0-11eb-81b2-6c415a4ccb41.png)
![image](https://user-images.githubusercontent.com/6733599/99497298-adb16880-29b0-11eb-98c9-edcbcf5ff740.png)

**Additional context**
It seems that the reason is related to the increased total voting power. On 2020-11-10, the total voting power was ~230 billion and the tally result was a little bit about 40%. Currently the total voting power increases to 268.68 billion, so I suspect that the proposal page is showing `tally = participated voting power / current total voting power` instead of `tally = participated voting power / total voting power at the end of voting period`.

**Comment by kwunyeung** [comment]
Thank you for the issue submission. We will look into this.
