### ISSUE TITLE
Failed to make a delegate tx with Ledger Nano S

### ISSUE THREAD

**Issue by terencesflam** [forbole/big-dipper#440]
I used Ledger Nano S on https://cosmos.bigdipper.live/

I could withdraw, but failed to make delegate tx after I confirmed the tx via Ledger Nano S:

![Screenshot 2020-12-17 at 5 56 27 PM](https://user-images.githubusercontent.com/34306139/102472355-31827180-4091-11eb-91c3-38a919f69dc3.png)

**Comment by kwunyeung** [comment]
@terencesflam You are probably sending the 2nd transaction too fast before the 1st transaction is fully executed. We can see how we can enhance the error message.
