### ISSUE TITLE
New Validator Does Not Exist Despite Successful Creation Tx

### ISSUE THREAD

**Issue by lightiv** [forbole/big-dipper#441]
**Describe the bug**

If you review the following link you can see my new validator is alive and well but on Big Dipper it says it does not exits.

https://akash.aneka.io/validators/akashvaloper14s4tlmlvy0vsps05csf8l80m7nqxmau3dfh330

**To Reproduce**
1. Go to 'https://akash.bigdipper.live/validator/akashvaloper14s4tlmlvy0vsps05csf8l80m7nqxmau3dfh330'
2. See error: 
Validator Details -
Validator does not exist.

**Expected behavior**

It should display the validator details same as:
https://akash.aneka.io/validators/akashvaloper14s4tlmlvy0vsps05csf8l80m7nqxmau3dfh330

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kwunyeung** [comment]
@lightiv thank you for the report. We will look into it. Thanks!

**Comment by kwunyeung** [comment]
@lightiv seems this is fixed from our latest deployment. Can you confirm if this can be closed?

**Comment by lightiv** [comment]
Thanks, it is fixed now.
