### ISSUE TITLE
Error that property 'gov' is not found in undefined

### ISSUE THREAD

**Issue by njmurarka** [forbole/big-dipper#443]
**Describe the bug**
We recently deployed our new COSMOS-based chain and grabbed the latest from Big Dipper's master branch, as we always do.

It used to work and given we have not made any changes at all to our code, we suspect something has changed on the Big Dipper end. Of course, this is conjecture. 

Here is what we get, over and over again:

`TypeError: Cannot read property 'gov' of undefined
big-dipper-server         |     at server/main.js:198:44
big-dipper-server         |     at Function.time (/home/ubuntu/output/bundle/programs/server/profile.js:273:30)
big-dipper-server         |     at /home/ubuntu/output/bundle/programs/server/boot.js:415:15
big-dipper-server         |     at /home/ubuntu/output/bundle/programs/server/boot.js:465:7
big-dipper-server         |     at Function.run (/home/ubuntu/output/bundle/programs/server/profile.js:280:14)
big-dipper-server         |     at /home/ubuntu/output/bundle/programs/server/boot.js:463:13
big-dipper-server         | sleeping before starting server`

Thanks.

**Comment by kwunyeung** [comment]
The latest master branch is targeting launchpad and the `setting.json` has been updated. Please follow https://github.com/forbole/big-dipper/blob/e143757cbe9f7bfcb196ebb4b166c71f073a3317/default_settings.json#L33

**Comment by njmurarka** [comment]
Thanks. That appears to have resolved it.
