### ISSUE TITLE
[Kava Big Dipper] Error on account screen after login with Ledger

### ISSUE THREAD

**Issue by terencesflam** [forbole/big-dipper#453]
The account screen is broken after login with Ledger.

![Screenshot 2021-01-16 at 10 09 36 AM](https://user-images.githubusercontent.com/34306139/104794494-f0da5d00-57e2-11eb-9d53-8368751bd1e9.png)

It will resume normal if I logged out. But the problem happens again if I hag login with Ledger.

**Comment by MonikaCat** [comment]
Fixed with #495
