### ISSUE TITLE
Transfer not found on block.  

### ISSUE THREAD

**Issue by edgir06** [forbole/big-dipper#456]
The block explorer actually told me to report the issue with a transfer.  It was ATOM from Coinbase to another wallet of mine.  I'm not sure if the update has anything to do with it but I would like to know where it is.

**Comment by philafrsh** [comment]
same happen to me???

**Comment by pdubb12003** [comment]
Same to me as well I filed issue also

**Comment by kwunyeung** [comment]
Thank you for the report. We have noticed the transaction indexing is not working properly at the moment. We are looking into the issue now.

**Comment by kwunyeung** [comment]
Turn out this is an issue in `Tendermint Core`.

Close as tracked by #472

**Comment by pdubb12003** [comment]
Will the funds still make it to my atomic wallet and also thank you for your prompt reply’s as I’ve been worried

**Comment by pdubb12003** [comment]
What do I do I’m new here

**Comment by kwunyeung** [comment]
You can always check your account balance with https://cosmos.bigdipper.live/account/{address}

**Comment by pdubb12003** [comment]
I see my account there but how long until it’s sent to original address thanks

**Comment by kwunyeung** [comment]
> I see my account there but how long until it’s sent to original address thanks

Transaction is committed in the next block. This is the instant finality of Tendermint Core. You may also search for the tx hash on Big Dipper. However, there is a performance issue in the current gRPC which may lead to some txs are not being indexed on our node. In case if you need specific help, please email us via info@forbole.com
