### ISSUE TITLE
Transfer Failure 

### ISSUE THREAD

**Issue by sminer10** [forbole/big-dipper#460]
Last night 19.02.2021, around 22:10 EST I initiated a transfer of around $75 of ATOM from my Coinbase account to my Atomic Wallet and have yet to see it completed. Please help.

**Comment by pdubb12003** [comment]
Same here

**Comment by sminer10** [comment]
Any news on a solution?

**Comment by pdubb12003** [comment]
Haven't heard anything here they must be still working on the problem someone said there was an update to the system yesterday so idk but it's frustrating

**Comment by kwunyeung** [comment]
Thank you for the report. This is a duplicate of #456.

**Comment by kwunyeung** [comment]
@pdubb12003 Yes there was an upgrade of Cosmos Hub yesterday which enable IBC. The Big Dipper now running is a newer version which may have issue targeting the latest build.
