### ISSUE TITLE
coinbase transaction link to cosmos big dipper shows up as an error: We're sorry - something's gone wrong.

### ISSUE THREAD

**Issue by stephanluke** [forbole/big-dipper#461]
Hello, I sent my ATOM tokens from Coinbase to my Atomic Wallet but the tokens are not showing.
When i click on the coinbase link to view transaction of my ATOM tokens transfer, Cosmos big dipper shows:We're sorry - something's gone wrong.
Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]10.14.6
 - Safari
 - 14.0.1

**Comment by edgir06** [comment]
Same happened to me

**Comment by kwunyeung** [comment]
Thank you for the report. This is a duplicate of #456.

**Comment by silvergorilla10** [comment]
Just happens to me as well, same exact issue
