### ISSUE TITLE
Transfer issue

### ISSUE THREAD

**Issue by Chedder30** [forbole/big-dipper#462]
I'm having trouble transferring my funds from my coinbase account to my atomic atom wallet it's still not showing up was wondering what the issue might be and if you guys can assist me with this thank you

**Comment by pdubb12003** [comment]
Same here

**Comment by kwunyeung** [comment]
There was a comment in #463 that it was an issue from Atomic Wallet. It could be they haven't upgraded their node to `cosmoshub-4`.
