### ISSUE TITLE
Lost transaction

### ISSUE THREAD

**Issue by empbac** [forbole/big-dipper#463]
Hi,
Last night I sent a $100 transaction from Coinbase to my Atomic Wallet, using my ATOM receive address there. Coinbase thinks the ATOM went out successfully but the transaction page to which they link is throwing an error:

https://cosmos.bigdipper.live/transactions/732BD51440AFA5E4283F6193D421915E7C2D92B0EC5B6E8049F5C38D94349BFE

Coinbase says: "2/18/2021 8:03 PM     Completed"

I'm not sure what happened to the 4.363599 ATOM that I sent, but I should have received it at address cosmos1g7ntd9a2zv8qdzfn0lsqe4kx7z5ysyl75vg8hf - I want to send more but am afraid to do so now.

If I'm barking up the wrong tree could someone direct me to where I might get the appropriate support?

Thanks,
Chris

**Comment by pdubb12003** [comment]
Same

**Comment by sminer10** [comment]
Same happened to me and then they closed my ticket after acknowledging it happened. So wtf is the solution? I'm just out the money I transferred or what?!

**Comment by pdubb12003** [comment]
Yea he closed mine too idk what’s going on

**Comment by empbac** [comment]
The issue for me was Atomic Wallet. I loaded my mnemonic phrase into 
wallet.cosmostation.io as recommended by one of the Cosmos techs through 
Reddit chat (r/cosmosnetwork) and my correct balance popped right up. I 
closed my Github ticket because this issue is resolved. People are 
saying that Atomic Wallet is no longer supported and not to use it.

Try the Cosmos subreddit, they'll reach out to you after you post.

https://www.reddit.com/r/cosmosnetwork/comments/lnqtcc/lost_transaction/

**Comment by empbac** [comment]
I have another update. Do not trust anyone on Reddit that reaches out to you through PM. They are all scammers.

And the Cosmos network seems to be experiencing major problems since their update the other night. Do not send any ATOM until this is ironed out.

**Comment by pdubb12003** [comment]
Thank you people have been saying use your memonic phrase on this website or that one but I know better thanks so much
