### ISSUE TITLE
Sent atom coins from coinbase to my atomic wallet

### ISSUE THREAD

**Issue by silvergorilla10** [forbole/big-dipper#465]
Hello, I sent my ATOM tokens from Coinbase to my Atomic Wallet but the tokens are not showing.
When i click on the coinbase link to view transaction of my ATOM tokens transfer, Cosmos big dipper shows:We're sorry - something's gone wrong.
Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue.
The transaction was done on my 
iPhone 11 phone.
iOS 14.4

**Comment by msky32** [comment]
This is happening to me too.  Sent my ATOM tokens out of Coinbase and not showing up. Says to leave an issue with Github.  No one seems to be helping.  Are you getting help?

**Comment by silvergorilla10** [comment]
No, no help. Hopefully they will figure out the bug and all of our transactions will go through

**Comment by msky32** [comment]
I hope so too.  I filed an issue just like yours.  Thanks

**Comment by kwunyeung** [comment]
If this is about Atomic Wallet, please report to https://atomicwallet.io/.

In the meantime, you can check your balance with https://cosmos.bigdipper.live/account/{address}

**Comment by silvergorilla10** [comment]
Hey just an FYI, I still am not showing my balance in my atomic wallet for
ATOM coins but I just checked the blockchain using my atomic wallet atom
address and it is now showing that my coins are available...before it
showed zero. Hopefully we get our tokens really soon.

**Comment by msky32** [comment]
I’m not seeing anything on mine yet.  No one is helping at Atomic Wallet either.  Not sure what to do now.

**Comment by silvergorilla10** [comment]
I read somewhere that they restarted the node and this is why were
experiencing this problem. I sent my coins around 4pm yesterday and just
now it’s showing a hash transaction ID. The support teams everywhere are
slammed. Just stay patient I’m sure you will eventually be able to view you
transaction details on the blockchain l.

**Comment by msky32** [comment]
Thank you for the info.  I bet they are slammed.

**Comment by msky32** [comment]
I see mine when I click on the link now but not in Atomic wallet yet.  Also shows a new address to send to .  Does yours?

**Comment by silvergorilla10** [comment]
So once my transaction showed up on the blockchain it took like another 5-7
hours I’d say for it to finally show up in my atomic wallet. I just sent
another cosmos transaction from my wife’s coinbase account to the same
atomic wallet and it’s doing the same thing. So don’t worry you’ll have
your coins soon. Really is nerve racking to say the least

**Comment by msky32** [comment]
Did you actually have to do anything or did you just wait it out?  Thanks so much for your help.  It’s been nerve racking because I’m new to this !

**Comment by silvergorilla10** [comment]
No problem, I know the feeling very well. I just waited it out. Once you
see your transaction on the blockchain it’s a matter of time.

**Comment by kwunyeung** [comment]
You can always check your account balance with https://cosmos.bigdipper.live/account/{address}

**Comment by silvergorilla10** [comment]
Hey did you get your atom tokens yet?

**Comment by silvergorilla10** [comment]
Hey,
So I was having an issue with my second transaction with my atom tokens,
showed on the blockchain but wasn’t showing in my atomic wallet, I’ve since
went on my desktop version of atomic wallet and version 2.27.1 is out and
the very first fix is the atom stargate support. So once I updated all my
atom tokens showed up. Hope you already got your tokens. Good luck
