### ISSUE TITLE
Sent ATOM from Coinbase not receiving 

### ISSUE THREAD

**Issue by msky32** [forbole/big-dipper#466]
Hi, 
I sent my ATOM tokens from Coinbase to my Atomic Wallet but the tokens are not showing.
When i click on the coinbase link to view transaction of my ATOM tokens transfer, Cosmos big dipper shows:We're sorry - something's gone wrong.
Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue.
The transaction was done on my
iPhone XS 
13.6.1

**Comment by Johnnyro9** [comment]
same exact thing just happened to me...ugh can someone please help?

**Comment by revtd** [comment]
Same issue! Still not going through!

**Comment by kwunyeung** [comment]
If this is about Atomic Wallet, please report to https://atomicwallet.io/.

In the meantime, you can check your balance with https://cosmos.bigdipper.live/account/{address}

**Comment by kwunyeung** [comment]
Tracked in #472
