### ISSUE TITLE
Transferring ATOM from coinbase

### ISSUE THREAD

**Issue by shahabrb** [forbole/big-dipper#467]
**Describe the bug**
Hi,
I sent my ATOM tokens from Coinbase to my Atomic Wallet but the tokens are not showing.
When i click on the coinbase link to view transaction of my ATOM tokens transfer, Cosmos big dipper shows:We're sorry - something's gone wrong.
Please try to refresh the page and see if the problem is gone. If the problem keeps happening, please consider filing a Github issue.

**Comment by stevewea** [comment]
Same happened to me.  Either the address that is giving us is wrong, or the transaction lookup service is not working right now (maybe upgrade related)

I was able to enter my destination address and see my ATOM are there:  https://cosmos.bigdipper.live/

So I think it arrived just fine, I just can’t do anything with the ATOM until they fix whatever is going wrong.

**Comment by kwunyeung** [comment]
If this is about Atomic Wallet, please report to https://atomicwallet.io/.

In the meantime, you can check your balance with https://cosmos.bigdipper.live/account/{address}
