### ISSUE TITLE
Funds did not get Received. 

### ISSUE THREAD

**Issue by JNBINVEST** [forbole/big-dipper#469]
I sent ATOM from Coinbase to my ATOM wallet in Atomic wallet and never received the funds. Why?

**Comment by kwunyeung** [comment]
If this is about Atomic Wallet, please report to https://atomicwallet.io/.

In the meantime, you can check your balance with https://cosmos.bigdipper.live/account/{address}

**Comment by JNBINVEST** [comment]
Thank you for this information. I can see my balance at the link you provided. I will check with Atomic Wallet as to why not received. 

Derrick JnBaptiste
