### ISSUE TITLE
Funds not received on cosmostation 

### ISSUE THREAD

**Issue by revtd** [forbole/big-dipper#470]
I sent 16.77 ATOM from Coinbase to cosmostation but no new ATOM are showing up in my cosmostation wallet.  It shows as sent but pending on Coinbase. The block explorer shows an error message for hub-4. On cosmostation (see pictures) it shows the transaction in my history but when I open the transaction it shows no information and If I try to share the transaction history for that transaction the app crashes. Using iPhone with up to date iOS. 
![708C8557-4F4E-48E0-8AC2-A6E31A0C7BBF](https://user-images.githubusercontent.com/79368677/108600061-bffdc280-7362-11eb-8334-2424dbad27de.jpeg)
![A381C68D-4D8F-49E0-8872-DB173DEDADFA](https://user-images.githubusercontent.com/79368677/108600062-c0965900-7362-11eb-8d34-7cfda0c9d82d.png)

**Comment by kwunyeung** [comment]
If this is about Cosmostation Wallet, please report to https://www.cosmostation.io/.

In the meantime, you can check your balance with https://cosmos.bigdipper.live/account/{address}
