### ISSUE TITLE
i sent 230 atoms to my atomic wallet yesterday, haven't received yet please tell what happend to my coins

### ISSUE THREAD

**Issue by ba1ha0xu7** [forbole/big-dipper#471]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kwunyeung** [comment]
If this is about Atomic Wallet, please report to https://atomicwallet.io/.

In the meantime, you can check your balance with https://cosmos.bigdipper.live/account/{address}
