### ISSUE TITLE
ATOM sent but didn’t arrive 

### ISSUE THREAD

**Issue by chenrizig** [forbole/big-dipper#473]
**Describe the bug**

6.792 ATOM sent from Coinbase to Ledger Live on 18th February 2021, it didn’t arrive.

Transaction 

13F66F2A29CACE8BB9D2893373CD7DD7903F072CF3606EF6DD607C25E798B60F

**Expected behavior**
I expected to receive 6.792 ATOM in my Ledger Live account.

**iPad (please complete the following information):**
 - OS: IOS 14.4
 - Browser Safari 
 - Version 87.0.4280.77
 - Coinbase App on IOS version 9.11.0
 - Ledger live App on IOS version 2.21.2 (225)

**Comment by kwunyeung** [comment]
I don't see any problem in the explorer. The transaction is shown https://cosmos.bigdipper.live/transactions/13F66F2A29CACE8BB9D2893373CD7DD7903F072CF3606EF6DD607C25E798B60F

Seems this is an issue on how Ledger Live display information on the chain. You may contact Ledger if you face any issue regarding Ledger and Ledger Live.
