### ISSUE TITLE
Unable to look up ATOM transaction

### ISSUE THREAD

**Issue by stevewea** [forbole/big-dipper#474]
**Describe the bug**
Coinbase gives the following link to look up ATOM transfer transaction: https://cosmos.bigdipper.live/transactions/B7E9718AA2FDB70AD35DE23196A0DCBE00626EC296C825EF9E537B0E8CA9D486
This link returns the error: "We're sorry - something's gone wrong."
Is this because of the missing index?  Or does Coinbase need to update the transaction reference links since the Starport update?

**To Reproduce**
1. Go to Coinbase and transfer ATOM from Coinbase to AtomicWallet 
2. In Coinbase, view transaction details
3. Click the link that Coinbase provides (eg., https://cosmos.bigdipper.live/transactions/B7E9718AA2FDB70AD35DE23196A0DCBE00626EC296C825EF9E537B0E8CA9D486 )
4. User is redirected to cosmos.bigdipper.live and gets "We're sorry - something's gone wrong."

**Expected behavior**
Click link from Coinbase, and should see the transaction status

**Screenshots**

**Desktop & Smartphone (not client-dependent)
 - OS: repro on Windows 10 and iOS 14+
 - Browser: edge, safari
 - Version: n/a

**Additional context**
Transaction occurred on 2/19/2021.  Still seeing this error as of 2/21/2021

**Comment by kwunyeung** [comment]
@stevewea there are some issues in the SDK and we have trying to fix with the team. In the meantime, I have checked your transaction has been committed at block height `5213801`. 

Sender `cosmos1t5u0jfg3ljsjrh2m9e47d4ny2hea7eehxrzdgd` transferred `433494847uatom` to `cosmos1utehncwfsavzkhda6grw42xykv4vs8nrtq3075`.

You may check the balance of https://cosmos.bigdipper.live/account/cosmos1utehncwfsavzkhda6grw42xykv4vs8nrtq3075 as well.
