### ISSUE TITLE
DID NOT RECEIVE ASSESTS

### ISSUE THREAD

**Issue by JNBINVEST** [forbole/big-dipper#475]
My transaction shows as complete from Coinbase to Atomic Wallet but it never arrived to my wallet address. Why did I not receive these ASSESTS?

**Comment by pdubb12003** [comment]
I didn't receive my assets also and they still closed my issue filed didn't let me know if they'll arrive at atomic wallet or not smh been 3 days

**Comment by JNBINVEST** [comment]
Unbelievable what is the issue? In my case they were clearly sent to the correct cosmos address. They have to make it there, that is the whole point of the blockchain. Being left to wonder is the frustrating part.

**Comment by pdubb12003** [comment]
Same here counbase says sent and completed they’re stuck in blockchain and it feels as if the mods are not trying to make sure we get them back

**Comment by pdubb12003** [comment]
Update: download the official wallet of cosmos (use google search and make sure it's from official website!!!) import your wallet from atomic with your 12 word mnemonic phrase you can find in settings and you'll be able to keep your cosmos there in that wallet send back to counbase or delegate guessing it's a problem with atomic good luck guys

**Comment by JNBINVEST** [comment]
Thank you for the update.  I will try this, hopefully it works.

**Comment by msky32** [comment]
I sent ATOM from Coinbase to Atomic wallet but never received them .  I see the balance seems to be stick and not going to Atomic wallet.  Is there some help with understanding the process of retrieving them to send to Cosmos wallet?   I’m very confused on how to do this process you explain above.

**Comment by pdubb12003** [comment]
Go to the App Store or google play store or if you’re using a pc download the Cosmostation once you do this you’re going to enter the 12 words that’s your mnemonics in the atomic wallet settings copy those and enter them into the cosmos station and create your wallet there from there you’ll be able to keep them or send them to another exchange hope this helps

**Comment by msky32** [comment]
Ok I will try that.  Thank you so much.  This is all new to me.

**Comment by msky32** [comment]
When I’m in Cosmostation do I click on “create” wallet and then click on Cosmo to enter words?  Or do I click on “import” ?

**Comment by pdubb12003** [comment]
You have to write down the 12 secret letters that are in the settings of your atomic wallet under private keys click the top one and it will reveal those words .... write them down then download the Cosmostation app on iOS App Store or google play store once you donthat click restore wallet a screen with blank spaces will pop up number 1 thru 25 or so anyways just enter the 12 and you’ll have them you can send them back to Coinbase from there or delegate them on cosmos station to earn rewards

**Comment by msky32** [comment]
Ok

**Comment by msky32** [comment]
Oh my gosh I did it!  Thank you SO much!

**Comment by pdubb12003** [comment]
No problem I had the same problem and GitHub moderators were of no help I thought mine were lost thank goodness for youtube best regards

**Comment by kwunyeung** [comment]
@pdubb12003 your issue was closed as it was a duplicate to the same issue reported before. The issue was from Atomic Wallet as they didn't show the updated account balance in `cosmoshub-4`.

To check your balance with Big Dipper, you can always visit https://cosmos.bigdipper.live/account/{address}. This will query the chain directly and report with the latest balance of the account. We welcome any questions and issue report to us regarding Big Dipper.

**Comment by JNBINVEST** [comment]
This worked for me as well! Thank you!!

**Comment by pdubb12003** [comment]
I’m glad guys I had originally bought mine to trade for cardanos but ended up delegating them on the Cosmostation for 10.36 % compared to Coinbase 5%

**Comment by kwunyeung** [comment]
Please always consider delegating to Forbole 🤣

**Comment by pdubb12003** [comment]
After this fiasco I’m going to need 100 cosmos up front 😭😭😭😭😭
