### ISSUE TITLE
no con pub key? crypto.com croeseid testnet 2

### ISSUE THREAD

**Issue by nebkas** [forbole/big-dipper#477]
**Describe the bug**
I get thousands of `"no con pub key?"` messages in the log. I suspect thats why I don't get infos on the validators tab or details of the validator

**To Reproduce**
1. starting `meteor --settings settings.json`
2. Click on Validators

**Screenshots**
![Bildschirmfoto vom 2021-02-27 02-16-19](https://user-images.githubusercontent.com/44835587/109368671-89fc9900-78a2-11eb-8134-652f835814b3.png)
![Bildschirmfoto vom 2021-02-27 02-21-14](https://user-images.githubusercontent.com/44835587/109368678-8e28b680-78a2-11eb-98c4-b072a59c6525.png)
![Bildschirmfoto vom 2021-02-27 02-13-22](https://user-images.githubusercontent.com/44835587/109368685-91bc3d80-78a2-11eb-89e5-af672952c7e1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser:  all
 - branches `kwun/v0.39.x-4, v0.39.x to v0.39.x-4`
 - crypto.com node binary `croeseid v0.8.1`(A version based on the patched release of Cosmos SDK 0.40.1)

**Additional context**
Thanks for your help in advance. Please don't be too hard with me, its my first github issue

**Comment by kwunyeung** [comment]
Please use the latest commit from https://github.com/forbole/big-dipper/tree/kwun/stargate

**Comment by nebkas** [comment]
I tested it too with the old crypto.com binary and it didnt worked. crypto.com updated binary today and now everything is working out of the box :)
