### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined kwun/stargate

### ISSUE THREAD

**Issue by nebkas** [forbole/big-dipper#480]
**Describe the bug**
Starting "node main.js" ends up with:

```
TypeError: Cannot read property 'find' of undefined
    at module (both/utils/coins.js:22:31)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /home/nebkas/output/bundle/programs/server/app/app.js:4944:1
    at /home/nebkas/output/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /home/nebkas/output/bundle/programs/server/boot.js:226:21
    at /home/nebkas/output/bundle/programs/server/boot.js:464:7
    at Function.run (/home/nebkas/output/bundle/programs/server/profile.js:280:14)
    at /home/nebkas/output/bundle/programs/server/boot.js:463:13
```

**To Reproduce**
1. ./build.sh
2.  cd programs/server && npm install)
3.  export MONGO_URL='mongodb://user:password@host:port/databasename'
4.  export ROOT_URL='http://example.com'
5.  export MAIL_URL='smtp://user:password@mailhost:port/'
6.  node main.js

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kwunyeung** [comment]
For production, please put the content of the `settings.json` in the specific environment variable.

https://docs.meteor.com/environment-variables.html#METEOR-SETTINGS

**Comment by nebkas** [comment]
Uff, may you have a concrete example for me. In which file I put the variables, or how its look like. I'm pretty new to this things with meteor etc

**Comment by nebkas** [comment]
I got it to work
