### ISSUE TITLE
The UX of "donation" which may cause confusion

### ISSUE THREAD

**Issue by terencesflam** [forbole/big-dipper#49]
**Is your feature request related to a problem? Please describe.**
Currently, there is a "donation" at the bottom on every page of Big Dipper. That works fine in most of the circumstances. But this may cause confusion if users are visiting the pages of validators as they may not know who they will be donating to.

**Describe the solution you'd like**
Some fine-tuning works on the visualization may help. [Etherscan](https://etherscan.io/) is a reference.

**Comment by kwunyeung** [comment]
Do you mean changing the footer like Etherscan? That will break the current UX. What make you confuse?

**Comment by ztsai** [comment]
I think changing the footer color will be sufficient to distinguish between the footer and the actual content

**Comment by kwunyeung** [comment]
Would it be too annoying if we have another colour bar on screen? Especially when it's on mobile. Currently we have fixed header and footer as we have transactions and blocks with scroll to load more, which I insist to have this. Pagination is old fashioned and not mobile friendly. We can't just adapt how Etherscan and Coingecko do with large footer and high contrast background colour. Need to think of a better UX if this makes confusion.

**Comment by terencesflam** [comment]
For example, if I am visiting the page of Forbole on Big Dipper, I am not sure if the donation means donate to Forbole or donate to Big Dipper.
