### ISSUE TITLE
Proposer validator info undefined

### ISSUE THREAD

**Issue by dpodyachev** [forbole/big-dipper#493]
**Describe the bug**
Proposer Validator link undefined with link like https://testnet.explorer.agoric.net/validator/undefined

**To Reproduce**
1. Open blocks list, for example https://testnet.explorer.agoric.net/blocks
2. Click on any Height (right column)
3. Check Proposer Validator link (https://testnet.explorer.agoric.net/validator/undefined)

**Expected behavior**
https://testnet.explorer.agoric.net/validator/1AC8D58222BD4B63B301F0850388670720172945 instead of https://testnet.explorer.agoric.net/validator/undefined

**Screenshots**
![image](https://user-images.githubusercontent.com/17184568/112902929-881b3500-90ef-11eb-89ff-e21cec93881c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Browser Firefox
 - Version  87.0 (64-bit)

**Comment by kwunyeung** [comment]
Thank you @dpodyachev ! Nice catch!
