### ISSUE TITLE
NaN on average block time

### ISSUE THREAD

**Issue by futurechimp** [forbole/big-dipper#500]
**Describe the bug**

I'm running Big Dipper at https://testnet-finney-blocks.nymtech.net/

Everything looks great except for one thing: Average Block Time is showing as NaN. 

**To Reproduce**
1. Go to 'https://testnet-finney-blocks.nymtech.net/'
2. View the block time

**Expected behavior**

I expect that the block time will show as a float

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium 
 - Version: 89

**Additional context**

I must have a setting wrong, but I'm not quite sure what it is. Relevant settings might be:

```
    "remote": {
        "rpc": "https://testnet-finney-validator.nymtech.net",
        "api": "http://testnet-finney-validator.nymtech.net:1317"
    },
```

The `rpc` endpoint is nginx proxying 26657, see e.g. https://testnet-finney-validator.nymtech.net which shows all the normal rpc methods happily. I assume those are correct.

Having taken a look through the code (checked out at tag `v0.41.x-7`), there aren't that many places I would expect to get `NaN`. One is on [line 355](https://github.com/forbole/big-dipper/blob/0d9d65f9a878382fdbfb9925df3c05f541d2d92a/imports/api/records/server/methods.js#L355) of `methods.js`

```
                averageBlockTime = averageBlockTime / analytics.length;
```

There doesn't seem to be a `if(analytics.length >0)` guard on that as the other ones have, but then again the method name suggests it's just doing aggregations once a day (?) so that seems like it's not the culprit. 

The [other instances](https://github.com/forbole/big-dipper/blob/0d9d65f9a878382fdbfb9925df3c05f541d2d92a/imports/api/records/server/methods.js#L270-L275) of this kind of code mostly do have a 0 guard. 

```
            if (analytics.length > 0){
                for (i in analytics){
                    averageBlockTime += analytics[i].timeDiff;
                    averageVotingPower += analytics[i].voting_power;
                }
                averageBlockTime = averageBlockTime / analytics.length;
```

I have looked through `mongo` and I do have analytics in my collection. Intriguingly, only the first one has a number in it: 

```
> db.analytics.find()
{ "_id" : "q9NASbvH326GRWfM3", "height" : 1, "precommits" : 0, "averageBlockTime" : 5000, "time" : "2021-03-22T18:13:48.525181843Z", "voting_power" : NaN }
{ "_id" : "KpdLpTxFvXeYBWqCJ", "height" : 2, "precommits" : 1, "averageBlockTime" : NaN, "timeDiff" : 1613251, "time" : "2021-03-22T18:40:41.776802991Z", "voting_power" : 1000 }
{ "_id" : "vk7qZoaywS2NqGt6d", "height" : 3, "precommits" : 1, "averageBlockTime" : NaN, "timeDiff" : 5018, "time" : "2021-03-22T18:40:46.794137623Z", "voting_power" : 1000 }
{ "_id" : "HyxPQcbaTbpYeufur", "height" : 4, "precommits" : 1, "averageBlockTime" : NaN, "timeDiff" : 5020, "time" : "2021-03-22T18:40:51.814339222Z", "voting_power" : 1000 }
{ "_id" : "DLXKfA76sXqY7svBh", "height" : 5, "precommits" : 1, "averageBlockTime" : NaN, "timeDiff" : 5024, "time" : "2021-03-22T18:40:56.838838681Z", "voting_power" : 1000 }
```

Starting a new local copy of Big Dipper at a non-zero initial block height also results in NaN here. 

I really like Big Dipper by the way! Thanks for making it.

**Comment by nebkas** [comment]
You have to set the genesis time in the settings.json. Something like:
"public":{
...

"genesisTime": "2021-03-25T01:00:14.268797802Z",

...

**Comment by kstoykov** [comment]
Setting the genesis time doesn't have no effect. They are still NaN.

**Comment by futurechimp** [comment]
Aha! Setting the `genesisTime` in `settings.json` worked perfectly (for me). Thanks @nebkas.

**Comment by kwunyeung** [comment]
@futurechimp should this be closed?

**Comment by futurechimp** [comment]
Yes please! Close it, everything is working well.
