### ISSUE TITLE
[stargate] Proposal vote tx with Ledger is disabled due to removal of legacy API

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#519]
In `stargate`, legacy api for broadcasting vote txs is removed. Ledger voting is disabled at the moment as the Ledger txs broadcasting are still using the legacy api. We have to update broadcasting the txs with protobuf gateway api for vote txs.

**Comment by kwunyeung** [comment]
@MonikaCat should we migrate all txs to stargate format?

**Comment by MonikaCat** [comment]
@kwunyeung Yes, let's upgrade all of the txs. I've created an issue, we can track it here #529

**Comment by kwunyeung** [comment]
Ok closing this now.
