### ISSUE TITLE
don't log debug messages on client

### ISSUE THREAD

**Issue by ztsai** [forbole/big-dipper#52]
should probably avoid console.log on client side

![Screen Shot 2019-05-03 at 10 44 37 AM](https://user-images.githubusercontent.com/1817638/57117684-a9066e80-6d90-11e9-9a4d-c1eea0d775ea.png)

**Comment by kwunyeung** [comment]
Agree. Do you have any suggestion on logging packages so that it will get rid of the logs when we build the production package?
