### ISSUE TITLE
Time format should be shown under user's preference

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper#96]
All time now are displayed in different formats. Sometimes users may want to know the UTC time which is recorded on chain, sometimes they want to see the local time, and sometimes they may want to see how recent the time is.

Suggest to build a component which let users to choose which time format they would like to see. A simple click would toggle the formats and store the preference in localStorage. The preference apply to all Time display areas.

**Comment by ztsai** [comment]
next step, instead of hardcoding `format` and using `moment.tz.guess`, get it from user preference

**Comment by kwunyeung** [comment]
Need a way to show "time to now" as well.

**Comment by kwunyeung** [comment]
The current ux is fine. Reopen with a new issue if needed.
